/* @global requirejs */

requirejs.config({
  baseUrl: '/js',
  packages: [{
    name: 'highcharts',
    main: 'highcharts',
  }],
  paths: {
    actions: 'app/actions',
    components: 'app/components',
    pages: 'app/pages',

    // Adblock workarounds
    'components/common/analytics': 'app/yanalstic/component',
    'actions/analytics': 'app/yanalstic/actions',
    'actions/analytics/google-tag-manager': 'app/yanalstic/actions/goelgo-amg-ntareag',
    'actions/analytics/google-analytics': 'app/yanalstic/actions/goelgo-yanalstic',
    'actions/analytics/fb-analytics': 'app/yanalstic/actions/bf-yanalstic',

    // the path should NOT include the '.js' file extension.

    // Scripts from CDNs
    'jquery': 'https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.min',
    'jquery-ui': 'https://cdn.jsdelivr.net/npm/jquery-ui-dist@1.12.1/jquery-ui.min',
    'uikit': 'https://cdn.jsdelivr.net/npm/uikit@3.0.3/dist/js/uikit.min',
    'jsrender': 'https://cdn.jsdelivr.net/npm/jsrender@1.0.6/jsrender.min',
    'jquery-form': 'https://cdn.jsdelivr.net/npm/jquery-form@4.2.2/dist/jquery.form.min',
    'jquerySuggestions': 'https://cdn.jsdelivr.net/npm/suggestions-jquery@20.3.0/dist/js/jquery.suggestions.min',
    'moment': 'https://cdn.jsdelivr.net/npm/moment@2.24.0/min/moment-with-locales.min',
    'datepicker': 'https://cdn.jsdelivr.net/npm/js-datepicker@5.10.0/dist/datepicker.min',
    'promise': 'https://cdn.jsdelivr.net/npm/es6-promise/dist/es6-promise.auto.min',
    'socket.io': 'https://cdn.jsdelivr.net/npm/socket.io-client@2.3.0/dist/socket.io.slim',
    'ionRangeSlider': 'https://cdn.jsdelivr.net/npm/ion-rangeslider@2.3.1/js/ion.rangeSlider.min',
    'hammerjs': 'https://cdn.jsdelivr.net/npm/hammerjs@2.0.8/hammer.min',
    'Cookies': 'https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min',
    'highcharts': 'https://cdn.jsdelivr.net/npm/highcharts@8.0.4',
    'jquery-pjax': 'https://cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min',
    'fullcalendar': 'https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min',
    'inputmask': 'https://cdn.jsdelivr.net/npm/inputmask@5.0.3/dist/inputmask.min',
    'vimeo': 'https://cdn.jsdelivr.net/npm/@vimeo/player@2.11.0/dist/player.min',
    'smart-app-banner': 'https://cdn.jsdelivr.net/npm/smart-app-banner@2.0.0/dist/smart-app-banner.min',
    'youtube': 'https://www.youtube.com/iframe_api?noext',

    // Scripts from external providers
    'ymaps': 'https://api-maps.yandex.ru/2.1/?apikey=62d29dfb-c65a-41d7-8158-7bd09c6de734&lang=ru_RU',

    // Scripts from TraderNet
    'quotesObserverAndUpdater': 'https://tradernet.ru/93d6e842c835a6e009fae604035bf40e6e08c50f/quotesObserverAndUpdater.v2',
    'MutationSummary': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/mutation-summary',
    'iguanachart': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/iguanachart/iguanachart.min',
    'jqueryHammer': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/jquery.hammer',
    'jqueryMousewheel': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/jquery.mousewheel.min',
    'jqueryPeity': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/jquery.peity',
    'jGrowl': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/jquery.jgrowl.ru',
    'jNT': 'https://tradernet.com/require/93d6e842c835a6e009fae604035bf40e6e08c50f/app/state/jNT',
    '_t': 'https://tradernet.ru/require/93d6e842c835a6e009fae604035bf40e6e08c50f/js/i18n',
    'date.format': 'https://tradernet.ru/public/javascripts/js/date.format',

    // VENDOR скрипты
    'intlTelInput': '/js/vendor/intlTelInput/intlTelInput.min',
    'intlTelInput-utils': '/js/vendor/intlTelInput/utils',
    'jquery.ForceBankingCard': '/js/vendor/jquery.ForceBankingCard',
    'slick': '/js/vendor/slick.min',
    'wow': '/js/vendor/wow.min',

    // Скрипы проекта
    'commonjs': '/js/app/common',
    'f24TNSockets': '/js/app/f24TNSockets',
    'f24OrderNotifications': '/js/app/f24OrderNotifications',
    'f24AuthLogin': '/js/app/f24AuthLogin',
    'f24Catalog': '/js/app/f24Catalog',
    'f24CpsSubmit': '/js/app/f24CpsSubmit',
    'f24CpsTemplate': '/js/app/f24CpsTemplate',
    'f24MicroCharts': '/js/app/f24MicroCharts',
    'f24PageLoader': '/js/app/f24PageLoader',
    'f24Cart': '/js/app/f24Cart',
    'f24Margin': '/js/app/f24Margin',
    'f24ShopCard': '/js/app/f24ShopCard',
    'f24StockChart': '/js/app/f24StockChart',
    'f24StockChartModal': '/js/app/f24StockChartModal',
    'f24Timer': '/js/app/f24Timer',
    'f24TimerButton': '/js/app/f24TimerButton',
    'f24UserBalance': '/js/app/f24UserBalance',

    'Button': '/js/app/Button',
    'Routes': '/dist/components/Routes.bundle.min',
    'ShareButtons': '/js/vendor/share-buttons/share-buttons',

    'f24MenuLK': '/js/app/f24MenuLK',
    'f24SecureSession': '/js/app/f24SecureSession',
    'f24OrderBook': '/js/app/f24OrderBook',
    'f24Portfolio': '/js/app/f24Portfolio',
    'f24ProfileCurrencyConverter': '/js/app/f24ProfileCurrencyConverter',
    'f24RadioButtons': '/js/app/f24RadioButtons',
    'f24Recommendations': '/js/app/f24Recommendations',
    'f24Signup': '/js/app/f24Signup',
    'f24SignupDocumentUploader': '/js/app/f24SignupDocumentUploader',
    'f24SignupDocumentsSigning': '/js/app/f24SignupDocumentsSigning',
    'f24SignupPhoneConfirmation': '/js/app/f24SignupPhoneConfirmation',
    'f24Documents': '/js/app/f24Documents',
    'f24Withdrawal': '/js/app/f24Withdrawal',
    'f24History': '/js/app/f24History',
    'f24Terminal': '/js/app/f24Terminal',
    'f24InvestIdeas': '/js/app/f24InvestIdeas',
    'f24Investopedia': '/js/app/f24Investopedia',
    'f24InvestopediaDetail': '/js/app/f24InvestopediaDetail',
    'f24News': '/js/app/f24News',
    'f24NewsMore': '/js/app/f24NewsMore',
    'f24Pagination': '/js/app/f24Pagination',
    'f24Statistic': '/js/app/f24Statistic',

    'f24Notification': '/js/app/f24Notification',

    'f24DividendsCalendar': '/js/app/f24DividendsCalendar',
    'f24DividendsTable': '/js/app/f24DividendsTable',
    'f24Marquee': '/js/app/f24Marquee',
    'f24Search': '/js/app/f24Search',
    'f24Index': '/js/app/f24Index',

    'f24ServiceSpb': '/js/app/f24ServiceSpb',

    // Kendo Grid :: Used by CPS templates from TraderNet
    // 'kendo.menu.ex': 'js/kendo.menu.ex',
    'kendo.slider.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.slider.min',
    'kendo.numerictextbox.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.numerictextbox.min',
    'kendo.core.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.core.min',
    'kendo.userevents.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.userevents.min',
    'kendo.listview.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.listview.min',
    'kendo.grid.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.grid.min',
    'kendo.data.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.data.min',
    'kendo.selectable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.selectable.min',
    'kendo.selectable.min.new': 'kendo-ui-2018/kendo.selectable.min',
    'kendo.multiselect.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.multiselect.min',
    'kendo.filtermenu.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.filtermenu.min',
    'kendo.editable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.editable.min',
    'kendo.columnsorter.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.columnsorter.min',
    'kendo.reorderable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.reorderable.min',
    'kendo.groupable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.groupable.min',
    'kendo.pager.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.pager.min',
    'kendo.window.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.window.min',
    'kendo.sortable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.sortable.min',
    'kendo.columnmenu.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.columnmenu.min',
    'kendo.resizable.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.resizable.min',
    'kendo.mobile.pane.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.pane.min',
    'kendo.progressbar.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.progressbar.min',
    'kendo.excel.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.excel.min',
    'kendo.mobile.actionsheet.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.actionsheet.min',
    'kendo.ooxml.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.ooxml.min',
    'kendo.pdf.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.pdf.min',
    'kendo.datepicker.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.datepicker.min',
    'kendo.dateinput.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.dateinput.min',
    'kendo.binder.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.binder.min',
    'kendo.validator.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.validator.min',
    'kendo.draganddrop.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.draganddrop.min',
    'kendo.data.xml.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.data.xml.min',
    'kendo.data.odata.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.data.odata.min',
    'kendo.popup.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.popup.min',
    'kendo.dropdownlist.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.dropdownlist.min',
    'kendo.menu.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.menu.min',
    'kendo.button.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.button.min',
    'kendo.mobile.scroller.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.scroller.min',
    'kendo.list.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.list.min',
    'kendo.calendar.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.calendar.min',
    'kendo.calendar.min.new': 'kendo-ui-2018/kendo.calendar.min',
    'kendo.fx.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.fx.min',
    'kendo.mobile.shim.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.shim.min',
    'kendo.color.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.color.min',
    'kendo.mobile.popover.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.popover.min',
    'kendo.mobile.view.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.view.min',
    'kendo.maskedtextbox.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.maskedtextbox.min',
    'kendo.mobile.loader.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.mobile.loader.min',
    'kendo.drawing.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.drawing.min',
    'kendo.view.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.view.min',
    'kendo.combobox.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.combobox.min',
    'kendo.dataviz.treemap.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.dataviz.treemap.min',
    'kendo.dataviz.themes.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.dataviz.themes.min',
    'kendo.dataviz.core.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.dataviz.core.min',
    'kendo.autocomplete.min': 'https://tradernet.ru/public/javascripts/kendo-ui-2017.2.504/js/kendo.autocomplete.min',

    'iban': 'https://tradernet.ru/public/javascripts/js/iban',
  },
  shim: {
    'youtube': { exports: 'YT' },
    'ymaps': { exports: 'ymaps' },
    jsrender: ['jquery'],
    slick: ['jquery'],
  },
});

